version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
  - dependency-name: vuetify
    versions:
    - 2.4.11
    - 2.4.9
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.8.0
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.2.0
    - 2.3.0
  - dependency-name: vuetify-loader
    versions:
    - 1.7.2
